//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcYazGelProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class basvuruDurumu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public basvuruDurumu()
        {
            this.IME_bilgileri = new HashSet<IME_bilgileri>();
            this.staj_formu = new HashSet<staj_formu>();
        }
    
        public int basvuruDurumuId { get; set; }
        public Nullable<int> ogrNo { get; set; }
        public string basvuruDurumu1 { get; set; }
        public Nullable<int> kabulEdilenGun { get; set; }
        public Nullable<int> kabulEdilmeyenGun { get; set; }
    
        public virtual uye uye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IME_bilgileri> IME_bilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<staj_formu> staj_formu { get; set; }
    }
}
