//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcYazGelProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IME_bilgileri
    {
        public int IME_id { get; set; }
        public Nullable<int> ogr_no { get; set; }
        public string IMEYeri_ad { get; set; }
        public Nullable<System.DateTime> IME_baslangic { get; set; }
        public Nullable<System.DateTime> IME_bitis { get; set; }
        public Nullable<int> IMENotu { get; set; }
        public string IMEDonemiDonem { get; set; }
        public string basvuruDurumu { get; set; }
    
        public virtual uye uye { get; set; }
    }
}
