//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcYazGelProje.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBYazgelProjeEntities : DbContext
    {
        public DBYazgelProjeEntities()
            : base("name=DBYazgelProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<basvuruDurumu> basvuruDurumu { get; set; }
        public virtual DbSet<bolum> bolum { get; set; }
        public virtual DbSet<gorev> gorev { get; set; }
        public virtual DbSet<IME_bilgileri> IME_bilgileri { get; set; }
        public virtual DbSet<il> il { get; set; }
        public virtual DbSet<ilce> ilce { get; set; }
        public virtual DbSet<staj_formu> staj_formu { get; set; }
        public virtual DbSet<staj_yeri> staj_yeri { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<unvan> unvan { get; set; }
        public virtual DbSet<uye> uye { get; set; }
        public virtual DbSet<yonetici> yonetici { get; set; }
    }
}
