//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcYazGelProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class staj_yeri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staj_yeri()
        {
            this.IME_bilgileri = new HashSet<IME_bilgileri>();
            this.staj_formu = new HashSet<staj_formu>();
        }
    
        public int stajYeri_id { get; set; }
        public string S_adi { get; set; }
        public string S_faaliyet_alani { get; set; }
        public string S_telefon { get; set; }
        public string S_fax { get; set; }
        public string S_eposta { get; set; }
        public string S_adres { get; set; }
        public Nullable<int> il_id { get; set; }
        public Nullable<int> posta_kodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IME_bilgileri> IME_bilgileri { get; set; }
        public virtual il il { get; set; }
        public virtual ilce ilce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<staj_formu> staj_formu { get; set; }
    }
}
