//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcYazGelProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yonetici
    {
        public int yoneticiID { get; set; }
        public string yonetici_kullaniciAdi { get; set; }
        public string yonetici_Ad { get; set; }
        public string yonetici_Soyad { get; set; }
        public string yonetici_sifre { get; set; }
    }
}
